#!/usr/bin/env python3
# Author ID: jmay10

import sys

arguments = sys.argv
name = sys.argv[0]
var1 = sys.argv[1]
var2 = sys.argv[2]


#This function finds out which command line argument to use.
def x(y):
    return(y)

def helloWorld():
	print("Hello World")


if __name__ == '__main__':
    print("Variable1 = " + str(x(var1)))
    print("Variable2 = " + str(x(var2)))
    print("Script name = " + str(x(name)))
    print("The Script and Variables used = " + str(x(arguments)))
    helloWorld()
